apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloworld
  name: helloworld
spec:
  ports:
  - name: "3000-tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: helloworld
  type: ClusterIP